from middleware.modules.shared.services.service_names import (
    SERVICE_AUTH,
    SERVICE_DASHBOARD_PLACES,
    SERVICE_JOURNAL_HAPPENINGS,
    SERVICE_TRAVEL_PLANNER,
)

__all__ = [
    "SERVICE_AUTH",
    "SERVICE_DASHBOARD_PLACES",
    "SERVICE_JOURNAL_HAPPENINGS",
    "SERVICE_TRAVEL_PLANNER",
]
